# Site settings
title: ARDILLA Project
author:
  name: Loren Cassin Sackett
  email: sackettl@colorado.edu
description: "Project site for squirrel genomics alliance"

# Build settings
#remote_theme: jekyll/minima
theme: Cayman
#theme: Midnight
